name: Build and push

on:
  workflow_call:
    secrets:
      NUGETAPI:
        required: true
      DW_TOKEN_API:
        required: true
env:
  dwPackageVersion: ${{ format('{0}{1}', vars.RELEASEPREFIX, vars.PRERELEASEVERSION) }}
  dwRepo: ${{ github.event.repository.name }}
  #GITHUB_TOKEN: ${{ secrets.DWTOKEN }}
  GH_TOKEN: ${{secrets.DW_TOKEN_API}}
  
jobs:
  build-and-publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build --version-suffix $dwPackageVersion
    - name: Test
      run: dotnet test --no-build --verbosity normal
    #- name: Push Nuget Packages
    #  uses: EasyDesk/action-nuget-push@v1.0.0
    #  with:
    #    nuget-api-key: "${{secrets.NUGETAPI}}"
    #    publish-dir: "./**" # optional, default is .
    - run:  |
        echo ${{ secrets.DW_TOKEN_API }}
        gh api --method PATCH -H "Accept:application/vnd.github+json" /repos/dynamicweb/$dwRepo/actions/variables/PRERELEASEVERSION -f name='PRERELEASEVERSION' -f value='SETMEGODGODDAMMIT' 
    #  env:
    #    GH_TOKEN: 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
    #- run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
    #- run: gh api --method PATCH -H "Accept:application/vnd.github+json" /repos/dynamicweb/$dwRepo/actions/variables/PRERELEASEVERSION -f value='0005'
