name: Nuget push package

on:
  workflow_call:

jobs:
  call-workflow:
     uses: ./.github/workflows/common-build.yml

  build:
    needs: call-workflow
    runs-on: ubuntu-latest

    steps:
    - name: Push Nuget Packages
      uses: EasyDesk/action-nuget-push@v1.0.0
      with:
        nuget-api-key: "${{secrets.NUGETAPI}}"
        publish-dir: "./**" # optional, default is .
        
