name: Build and push

on:
  workflow_call:
    secrets:
      NUGETAPI:
        required: true
env:
  #packageVersion: ${{ format('{0}{1}', vars.RELEASEPREFIX, vars.PRERELEASEVERSION }}
  packageVersion: 'Alpha001'
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --version-suffix $packageVersion
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Push Nuget Packages
      uses: EasyDesk/action-nuget-push@v1.0.0
      with:
        nuget-api-key: "${{secrets.NUGETAPI}}"
        publish-dir: "./**" # optional, default is .
        
