name: Build

on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --version-suffix $NOW
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Push Nuget Packages to DEV feed
      uses: EasyDesk/action-nuget-push@v1.0.0
      with:
        publish-dir: "./**" # optional, default is .
        nuget-url: 'http://feed.dw-i001.nuget.dynamicweb-cms.com/v3/index.json'
